
name: Build and Publish Plugin
on:
  release:
    types:
      - published
jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      publish-token: ${{ secrets.PUBLISH_TOKEN }}
    steps:

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
        #checkout plugin-repository
      - uses: actions/checkout@v2
        with:
          repository: fazlizekiqi/envar
          ref: main
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle build
        run: chmod +x gradle
      - name: build and publish plugin
        run: |
          gradle buildPlugin
          gradle publishPlugin -PintellijPublishToken=${{ env.publish-token }}
